@startuml
'https://plantuml.com/class-diagram

interface MemberMapper{}

interface ReplyMapper{
+ selectAllReply(int articleNo): List<ReplyVO>
+ insertReply(ReplyVO reply): void
+ insertDepthReply(ReplyVO reply): void
+ updateReply(ReplyVO reply): void
+ deleteReply(int replyNo): void
}

class ReplyVO{
- int no
- int articleNo
- int memberNo
- String nickname
- String writeDate
- String content
- int groupNo
- int sequence
- int depth
- int hide

' 메서드 -------------
+ {static} createReply(int articleNo, int memberNo, String nickname, String content): ReplyVO
+ {static} createDepthReply(int articleNo, int memberNo, String nickname, String content, int depth, int grpNo): ReplyVO
+ {static} updateReply(int replyNo, String content): ReplyVO
+ ReplyVO()
+ toString()
+ getNo(): int
+ setNo(int no): void
+ getArticleNo(): int
+ setArticleNo(int articleNo): void
+ getMemberNo(): int
+ setMemberNo(int memberNo): void
+ getNickname(): String
+ setNickname(String nickname): void
+ getWriteDate(): String
+ setWriteDate(String writeDate): void
+ getContent(): String
+ setContent(String content): void
+ getGroupNo(): int
+ setGroupNo(int groupNo): void
+ getSequence(): int
+ setSequence(int sequence): void
+ getDepth(): int
+ setDepth(int depth): void
+ getHide(): int
+ setHide(int hide): void
}

interface ReplyDao{
- ReplyMapper replyMapper

+ selectAllReply(int articleNo): List<ReplyVO>
+ insertReply(ReplyVO reply): void
+ updateReply(ReplyVO reply): void
+ deleteReply(int replyNo): void

}

class ReplyDaoImpl


interface ReplyService{
- ReplyDao replyDao
- MemberMapper memberMapper

+ retrieveAllReply(int articleNo): List<ReplyVO>
+ registerReply(ReplyVO reply): void
+ modifyReply(ReplyVO reply): void
+ removeReply(int replyNo, int memberNo): void
}

class ReplyServiceImpl



class ReplyController{
- ReplyService ReplyServiceImpl

+ insertReply(@RequestParam("no") int grpNo,@RequestParam("articleNo") int articleNo,@RequestParam("content") String content,@RequestParam("depth") int depth, HttpServletRequest req): List<ReplyVO>
+ updateReply(@RequestParam("no") int replyNo,@RequestParam("articleNo") int articleNo,@RequestParam("content") String content): List<ReplyVO>
+ deleteReply(@RequestParam("no") int replyNo,@RequestParam("articleNo") int articleNo,HttpServletRequest req): List<ReplyVO>
}


@enduml